# Generated by Django 5.0.6 on 2024-06-29 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComprador', models.CharField(max_length=50)),
                ('mailComprador', models.EmailField(max_length=254)),
                ('direccionComprador', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('arribo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'inventario',
                'verbose_name_plural': 'inventarios',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComprador', models.CharField(max_length=50)),
                ('direccionComprador', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('horaPedido', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
